$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: cv-custom-train
display_name: Custom CV Training
type: command

inputs:
  train_images:
    type: uri_folder
  valid_images:
    type: uri_folder

code: .
environment: azureml:cv-custom-train-env:1.1

command: >
  python train.py
  --train_images ${{inputs.train_images}}
  --valid_images ${{inputs.valid_images}}

